# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HVAC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HVAC
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'HVACTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HVAC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFabric-tvOS

  target 'HVAC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
